# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='categories',
            field=models.CharField(max_length=80, verbose_name='دسته بندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange',
            field=models.CharField(max_length=80, verbose_name='بازار معاملاتی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id1',
            field=models.IntegerField(verbose_name='id'),
        ),
    ]
