# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20170528_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intradaytrades',
            name='trade',
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='buyer_count',
            field=models.CharField(default=1, max_length=80, verbose_name='تعداد خریداران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='close_price_change',
            field=models.CharField(default=1, max_length=80, verbose_name='آخرین قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='high_price',
            field=models.CharField(default=1, max_length=80, verbose_name='بیشترین قیمت معاملاتی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='low_price',
            field=models.CharField(default=1, max_length=80, verbose_name='کمترین قیمت معاملاتی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='open_price',
            field=models.CharField(default=1, max_length=80, verbose_name='اولین قیمت معاملاتی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradaytrades',
            name='real_close_price_change',
            field=models.CharField(default=1, max_length=80, verbose_name='تغییر قیمت پایانی نسبت به قیمت پایانی روز قبل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intradaytrades',
            name='real_close_price',
            field=models.CharField(max_length=80, verbose_name='قیمت پایانی معاملات با احتساب حجم مبنا'),
        ),
    ]
