# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20170528_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='intradaytrades',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='show.Company'),
            preserve_default=False,
        ),
    ]
