# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20170530_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id1',
            field=models.IntegerField(unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='intradaytrades',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='show.Company'),
        ),
    ]
