# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20170530_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(unique=True, verbose_name='id')),
                ('code', models.CharField(max_length=80, verbose_name='کد بورسی')),
                ('name', models.CharField(max_length=80, verbose_name='نام نماد')),
                ('english_name', models.CharField(max_length=80, verbose_name='نام انگلیسی نماد')),
                ('isin', models.CharField(max_length=80, verbose_name='isin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='show.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='intradaytrades',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='show.Company'),
        ),
    ]
